# Api http test requests

### Get cats
GET http://localhost:3000/api/v1/cats

### Get cat by id
GET http://localhost:3000/api/v1/cats/41

### Get cats by user id
GET http://localhost:3000/api/v1/cats/user/1

### Post new cat without image
POST http://localhost:3000/api/v1/cats
Content-Type: application/json

// owner pitää olla olemassa (eli olemassa oleva user)
{
  "cat_name": "Mirri",
  "weight": 5,
  "owner": 37,
  "filename": "f3dbafakjssssf4",
  "birthdate": "2020-10-12"
}

### Post new cat with image
POST http://127.0.0.1:3000/api/v1/cats HTTP/1.1
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="cat_name"

Kissa Kissanen
--MyBoundary
Content-Disposition: form-data; name="weight"

6
--MyBoundary
Content-Disposition: form-data; name="owner"

1
--MyBoundary
Content-Disposition: form-data; name="birthdate"

2023-10-08
--MyBoundary
Content-Disposition: form-data; name="file"; filename="cat.jpg"
Content-Type: image/jpg

< ./cat.jpg
--MyBoundary--

### Modify cat
PUT http://localhost:3000/api/v1/cats/41
Content-Type: application/json

{
  "cat_name": "Siiri THE Super cat",
  "weight": 5,
  "owner": 37,
  "filename": "f3dbafakjssssf4",
  "birthdate": "2020-10-12"
}

### Delete cat by id
DELETE http://localhost:3000/api/v1/cats/44


// User tests

### Get users
GET http://localhost:3000/api/v1/users

### Get user by id
GET http://localhost:3000/api/v1/users/37

### Post new user
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "name": "Joku",
  "username": "joku",
  "email": "new@metropolia.fi",
  "role": "user",
  "password": "password1"
}

### Modify user
PUT http://localhost:3000/api/v1/users/1
Content-Type: application/json

{
  "name": "Michael THE Brown",
  "username": "mbrown",
  "email":  "michael@metropolia.fi",
  "role": "admin",
  "password": "mike456"
}

### Delete user by id
DELETE http://localhost:3000/api/v1/users/1
