# Api http test requests

// Token expires based on JWT_EXPIRES_IN value. Paste new token here when expired.
// To get token: create new user, and post auth/login -> shows token
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1NSwibmFtZSI6IlV1c2kiLCJ1c2VybmFtZSI6InV1c2kiLCJlbWFpbCI6Im5ld0BtZXRyb3BvbGlhLmZpIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NjI5NzU1MjgsImV4cCI6MTc2MzA2MTkyOH0.pCXn7IgKxJVd1HQm6Y__2LRIJkbB0MgIQRfsMt8A5Qs

### Get cats
GET http://localhost:3000/api/v1/cats

### Get cat by id
GET http://localhost:3000/api/v1/cats/41

### Get cats by user id
GET http://localhost:3000/api/v1/cats/user/1
Authorization: Bearer {{token}}

### Post new cat without image
POST http://localhost:3000/api/v1/cats
Content-Type: application/json
Authorization: Bearer {{token}}

// owner pitää olla olemassa (eli olemassa oleva user)
{
  "cat_name": "Herra Hakkarainen",
  "weight": 5,
  "owner": 1,
  "filename": "f3dbafakjssssf4",
  "birthdate": "2020-10-12"
}

### Post new cat with image
POST http://127.0.0.1:3000/api/v1/cats HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="cat_name"

Kissa Koiranen
--MyBoundary
Content-Disposition: form-data; name="weight"

6
--MyBoundary
Content-Disposition: form-data; name="owner"

1
--MyBoundary
Content-Disposition: form-data; name="birthdate"

2023-10-08
--MyBoundary
Content-Disposition: form-data; name="file"; filename="cat.jpg"
Content-Type: image/jpg

< ./cat.jpg
--MyBoundary--

### Modify existing cat
PUT http://localhost:3000/api/v1/cats/70
Content-Type: application/json

{
  "cat_name": "Siiri Kissanen",
  "weight": 5,
  "owner": 60,
  "filename": "f3dbafakjssssf4",
  "birthdate": "2020-10-12"
}

### Delete cat by id
DELETE http://localhost:3000/api/v1/cats/67


// User tests

### Get users
GET http://localhost:3000/api/v1/users
Authorization: Bearer {{token}}

### Get user by id
GET http://localhost:3000/api/v1/users/1

### Post new user (username needs to be unique)
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "name": "Uusi Ihminen",
  "username": "ihminen",
  "email": "new@metropolia.fi",
  "role": "user",
  "password": "password1"
}

### Post auth/login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "username": "uusikuusi",
  "password": "password1"
}

### Get my user info
GET http://localhost:3000/api/v1/auth/me
Authorization: Bearer {{token}}

### Get my cats
GET http://localhost:3000/api/v1/cats/user
Authorization: Bearer {{token}}

### Modify existing user
PUT http://localhost:3000/api/v1/users/1
Content-Type: application/json

{
  "name": "Dumbledore SUPER Admin",
  "username": "albus",
  "email":  "albus@metropolia.fi",
  "role": "admin",
  "password": "thisShouldBeHashed"
}

### Delete user by id
DELETE http://localhost:3000/api/v1/users/58

### Delete cat by user
DELETE http://127.0.0.1:3000/api/v1/users/37
